# WPI Cloud - vagrant app help
# by Dima Minka (https://dima.mk)
# https://cloud.wpi.pw

NAME:

  wpi vagrant app

DESCRIPTION:

  Add to config new app via wizard. Vagrant will create the app on vagrant up or vagrant reload.

SYNOPSIS:

  wpi vagrant app <command>

GLOBAL_PARAMETERS:

  - param: --help | -h
    description: Gets help on WPI, or on a specific command.
  - param: --local | -l
    description: Run the WPI localy from downloaded repository.
